# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Project

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        continue-on-error: true
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

      - name: Deploy Test Reports to Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: true
          deploy_key: ${{ secrets.SITE_DEPLOY_KEY }}
          external_repository: engteam14/website2
          publish_branch: main
          publish_dir: ./core/build/reports
          destination_dir: testreports

      - name: Re-build to notify of errors
        continue-on-error: true
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

      - name: Create Jar
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: -p desktop dist

      - name: Deploy Jar
        uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: true
          deploy_key: ${{ secrets.SITE_DEPLOY_KEY }}
          external_repository: engteam14/website2
          publish_branch: main
          publish_dir: ./desktop/build/libs
          destination_dir: game
          keep_files: true

  documentation:
    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build

      - name: Generate Documentation
        continue-on-error: true
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: -p core javadoc

      - name: Deploy Documentation to Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: true
          deploy_key: ${{ secrets.SITE_DEPLOY_KEY }}
          external_repository: engteam14/website2
          publish_branch: main
          publish_dir: ./core/build/docs/javadoc
          destination_dir: javadoc

